--- #YAML:1.0
# http://module-build.sourceforge.net/META-spec.html
distribution_type: module
name: DateTime-Format-IBeat
date: 26 January 2004
author: EMARTIN
version: 0.161
license: perl

conflicts: {}

build_requires:
  Test::More: 0.47
recommends:
  Test::Pod: 1.02
  Test::Signature: 1.05
requires:
  DateTime: 0.18

private:
  directory:
    - t

provides:
  DateTime::Format::IBeat:
    file: lib/DateTime/Format/IBeat.pm
    version: 0.16

dynamic_config: 0