--- #YAML:1.0
build_requires:
  Test::More: 0.47
conflicts: {}
distribution_type: module
license: perl
name: DateTime-Format-IBeat
recommends:
requires:
  DateTime: 0.09
  Carp: 1.01
version: 0.15
generated_by: docmaker version 0.89
